### ISSUE TITLE
Update SDK Documentation to include getting a user token before making calls

### ISSUE THREAD

**Issue by Spencer-Mosley** [lumapps/lumapps-sdk#56]
https://lumapps.github.io/lumapps-sdk/cli.html

The link to the page above has been causing some confusion for users since it doesn't explain that users now need to obtain a token before making these calls.
Could we update this to include the explanation and example of how to makes these calls by getting tokens as well.
Thanks

**Comment by ulodciv** [comment]
@Spencer-Mosley 

I added the possibility to make use of user/getToken implicitly, which makes a one-step process what used to require two steps. I added an example at the end of https://lumapps.github.io/lumapps-sdk/cli.html
